version: "3.8"

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Exposes MongoDB on localhost:27017
    volumes:
      - mongo_data:/data/db # Persist MongoDB data
    networks:
      - mern-network

  # Backend Service (Node.js)
  backend:
    build:
      context: ./server # Path to the server directory where the Dockerfile is located
    container_name: mern-backend
    ports:
      - "5000:5000" # Exposes the backend API on localhost:5000
    environment:
      - DB_URI=mongodb://mongo:27017/mern-app # MongoDB URI connecting to the 'mongo' service
    depends_on:
      - mongo # Ensures MongoDB starts first
    networks:
      - mern-network

  # Frontend Service (React with Vite)
  frontend:
    build:
      context: ./client # Path to the client directory where the Dockerfile is located
    container_name: mern-frontend
    ports:
      - "5173:5173" # Exposes the Vite development server on localhost:5173
    depends_on:
      - backend # Ensures backend starts first
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_data:
